language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
script: mvn -P run-its package
after_success:
- travis/deploy.sh
env:
  global:
  - secure: P1V34H+1mJqgsfG+YCHLIVNYKjiSpJLdzksa7zGJg3iQEANYbRPnJvrnNLOm2thrdJPZWL21eCntw43AgS2PBHmGpI/Ay96P3Kg1hoojWYFhg8cDkISHR7Si4Hm1pFPGTg/ZU0xpYjsP2chxR6mOvGvSJqu8PrRAq08y8OiBoO/sPjzFdHatHhUY3B6sP1rsUlyfmbN9TQzmRC+vHh+KDKeQjQhYlRageMnCE/MAFU1E3SoPE0Iw5158gVtFQn9vg2+/Ws9smBUCADCDFA3KhS5wYzpR7Uf79FyqnUJT89QmsOzw960d8QMa3Vxb3VA27RYwzYqzYUDcVd4HpMyklk0bfmiuequc8C0cTb+59vn8n4H7JO4WRYiHDn/gSyeiMG5m8yEYeK6/maz55KdFoWysI6sgGxHaR+HbybfNPHI29ws6mX6bAhCowNIRu70H9bbHEa1JaRcYsjJQiPl/Eui4BnyakLkCMF9NnsuOAaYBUfcbREs8GWxYjCUD9j0bnOlSRTs+TI48F5LJm+zBJKFuYwOpNi/GrPqRc0g32zTzwKz/X24uL2eAAH/slq4ciaqXBSA9R4sqoMhurgiR8HhS74M0fEneoDRYuXvQhFyPIVx/ZCN9B8c0SKruqIIyYGiZq3WuzVca2tMgIhC0ivwIyd8z8p6gWWcg4x92re8=
  - secure: A/eNdKOGQZii+2Yw+Zj6OdSsWc42iwRV5gDAP8tQsOLRsorqETT8FwJPziZZL21vBvshG/qf3qmrs8nA2bwm6Y6gECMAmXH9HNkcmhXNmN9Mlra5SGzuAMj1eDV0BYFpwqt86ydnjPgt+OWiDNGll5V8V4vDifMI0n6KL1wXpx9KtiM3ru3eNl+MUxb39gdhk2umj198N6kSmZe/momIQ9qSed5NLaMqlm7m8GtTtqAtgIfUuMHCHV1Y/Idbq54ZsU2g0fpfLTS/pnxJ7/rqNIcXM0smlKx/SZrqVk4s9zvPpQaDBKjx3uSikt1QbcKygzqWXix0QFHT8j/PBejTW/Xh3eGIb5RzyvCMW7TGozobVURRQocuVWud+fPRwFEnQq9BPz8C/o0WRJ2YjJPwtO70hDV9j9COd+KMi0IZpsqmf2+w+zNWtzlU50rcCWjVuKGuTuuyj2dI0rz8Pg/7XsZraUcKIR79/KZYsGcWQr7hzUf3djOjgQ6cF6eYf5v/XAnYi6n48lKrEd1x1TomK/0BnQCqjN3tovo9M1GKv+U2sVhb25pMMg9wha4bdNM1UZkk+caeqRkolPHoZPK0PdQtzFAA70j+2cFQfz3aS1/4dthMIRRDJTVbNFksHIGpsQOauVV+tIBjvhzLB5N3wgIZmuMZb3ouxfx02pRUqQc=
